### ISSUE TITLE
locator cannot be used to get xpos,ypos

### ISSUE THREAD

**Issue by bmidgley** [hybridgroup/cylon-sphero#52]
I've tried every method I can find to get locator to work.

1. readLocator calls the callback without xpos or ypos. err,data is:
```json
null, { sop1: 255,
  sop2: 255,
  mrsp: 4,
  seq: 59,
  dlen: 1,
  data: <Buffer >,
  checksum: 191 }
```

2. my.sphero.setDataStreaming called with 
n: 400, m: 1, pcnt: 0, dataSources: ['locator', 'accelOne', 'velocity', 'accelerometer']

on dataStreaming gets called with data objects that do not have xpos or ypos either:

```json
{ desc: 'Sensor Data Streaming',
  idCode: 3,
  event: 'dataStreaming',
  did: 2,
  cid: 17,
  packet: 
   { sop1: 255,
     sop2: 254,
     idCode: 3,
     dlenMsb: 0,
     dlenLsb: 13,
     dlen: 13,
     data: <Buffer ff 69 00 9b 0f dd 00 63 00 00 00 00>,
     checksum: 157 },
  xAccel: 
   { sensor: 'accelerometer axis X, filtered',
     range: { bottom: -32768, top: 32767 },
     units: '1/4096 G',
     value: [ -151 ] },
  yAccel: 
   { sensor: 'accelerometer axis Y, filtered',
     range: { bottom: -32768, top: 32767 },
     units: '1/4096 G',
     value: [ 155 ] },
  zAccel: 
   { sensor: 'accelerometer axis Z, filtered',
     range: { bottom: -32768, top: 32767 },
     units: '1/4096 G',
     value: [ 4061 ] },
  accelOne: 
   { sensor: 'acceleration one',
     range: { bottom: 0, top: 8000 },
     units: '1mG',
     value: [ 99 ] },
  xVelocity: 
   { sensor: 'velocity X',
     range: { bottom: -32768, top: 32767 },
     units: 'mm/s',
     value: [ 0 ] },
  yVelocity: 
   { sensor: 'velocity Y',
     range: { bottom: -32768, top: 32767 },
     units: 'mm/s',
     value: [ 0 ] } }
```

3. finally, the on locator callback is never called.  

my code for reference:

```javascript
var Cylon;

Cylon = require('cylon');

Cylon.robot({
  connections: {
    sphero: {
      adaptor: 'sphero',
      port: '/dev/rfcomm0'
    }
  },
  devices: {
    sphero: {
      driver: 'sphero'
    }
  },
  work: function(my) {
    var a, color;
    a = {};
    color = [0, 0, 0];
    my.sphero.on("locator", function(data, d2) {
      return console.log("onlocator", data, d2);
    });
    my.sphero.detectCollisions();
    my.sphero.setBackLed(192);
    my.sphero.setDataStreaming({
      n: 400,
      m: 1,
      pcnt: 0,
      dataSources: ['locator', 'accelOne', 'velocity', 'accelerometer']
    });
    my.sphero.configureLocator({
      flags: 0,
      x: 0,
      y: 0,
      yawTare: 0
    }, function(err, data) {
      return console.log("configure", err, data);
    });
    my.sphero.on("dataStreaming", function(data) {
      console.log(data);
      a.x = data.xAccel.value[0];
      a.y = data.yAccel.value[0];
      a.z = data.zAccel.value[0];
      a.one = data.accelOne.value[0];
      if (a.z > 8000) {
        return color[1] = 240;
      }
    });
    my.sphero.on("collision", function() {
      return color[0] = 240;
    });
    return every(5..second(), function() {
      var direction, shade;
      my.sphero.readLocator(function(err, data) {
        return console.log("readlocator", err, data);
      });
      shade = color[0] << 16 | color[1] << 8 | color[2];
      my.sphero.color(shade);
      if (color[0] > 0) {
        color[0] -= 10;
      }
      if (color[1] > 0) {
        color[1] -= 10;
      }
      if (color[2] > 0) {
        color[2] -= 10;
      }
      if (shade === 0) {
        direction = ((new Date()).getTime() / 100) % 360;
        return my.sphero.roll(60, direction * 0);
      } else {
        return my.sphero.stop();
      }
    });
  }
});

Cylon.start();
```

I checked and the examples for using location aren't showing locations. Callbacks get objects that never contain xpos or ypos

debian@beaglebone:/usr/local/lib/node_modules/cylon-sphero/examples/locator$ node fluent-locator.js
I, [2015-09-13T19:36:19.220Z]  INFO -- : [Robot 1] - Starting connections.
I, [2015-09-13T19:36:19.239Z]  INFO -- : Connecting to Sphero 'sphero'...
I, [2015-09-13T19:36:21.230Z]  INFO -- : [Robot 1] - Starting devices.
I, [2015-09-13T19:36:21.403Z]  INFO -- : [Robot 1] - Working.
Setting up Collision Detection...
```json
data:
{ desc: 'Sensor Data Streaming',
  idCode: 3,
  event: 'dataStreaming',
  did: 2,
  cid: 17,
  packet: 
   { sop1: 255,
     sop2: 254,
     idCode: 3,
     dlenMsb: 0,
     dlenLsb: 7,
     dlen: 7,
     data: <Buffer 00 64 00 00 00 00>,
     checksum: 145 },
  accelOne: 
   { sensor: 'acceleration one',
     range: { bottom: 0, top: 8000 },
     units: '1mG',
     value: [ 100 ] },
  xVelocity: 
   { sensor: 'velocity X',
     range: { bottom: -32768, top: 32767 },
     units: 'mm/s',
     value: [ 0 ] },
  yVelocity: 
   { sensor: 'velocity Y',
     range: { bottom: -32768, top: 32767 },
     units: 'mm/s',
     value: [ 0 ] } }
```
...

debian@beaglebone:/usr/local/lib/node_modules/cylon-sphero/examples/locator$ node locator.js
I, [2015-09-13T19:38:12.525Z]  INFO -- : [Robot 1] - Starting connections.
I, [2015-09-13T19:38:12.545Z]  INFO -- : Connecting to Sphero 'sphero'...
I, [2015-09-13T19:38:17.939Z]  INFO -- : [Robot 1] - Starting devices.
I, [2015-09-13T19:38:18.122Z]  INFO -- : [Robot 1] - Working.
Setting up Collision Detection...
```json
dataStreaming:
{ desc: 'Sensor Data Streaming',
  idCode: 3,
  event: 'dataStreaming',
  did: 2,
  cid: 17,
  packet: 
   { sop1: 255,
     sop2: 254,
     idCode: 3,
     dlenMsb: 0,
     dlenLsb: 7,
     dlen: 7,
     data: <Buffer 00 65 00 00 00 00>,
     checksum: 144 },
  accelOne: 
   { sensor: 'acceleration one',
     range: { bottom: 0, top: 8000 },
     units: '1mG',
     value: [ 101 ] },
  xVelocity: 
   { sensor: 'velocity X',
     range: { bottom: -32768, top: 32767 },
     units: 'mm/s',
     value: [ 0 ] },
  yVelocity: 
   { sensor: 'velocity Y',
     range: { bottom: -32768, top: 32767 },
     units: 'mm/s',
     value: [ 0 ] } }
```
...

**Comment by deadprogram** [comment]
That is some excellent research @bmidgley thank you so much for such a complete issue report. We'll look into it.

**Comment by bmidgley** [comment]
This was on original sphero. I will retest on sphero 2

On Tuesday, September 15, 2015, Ron Evans <notifications@github.com> wrote:

> That is some excellent research @bmidgley <https://github.com/bmidgley>
> thank you so much for such a complete issue report. We'll look into it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hybridgroup/cylon-sphero/issues/52#issuecomment-140497934>
> .
>


-- 
Brad Midgley

**Comment by bmidgley** [comment]
Whoops, it really was a sphero 2 on the first try. Firmware is 3.71, the latest.

**Comment by deadprogram** [comment]
Sorry, I am confused. Please elaborate, it did or it did not work for you on Sphero2? Thanks.

**Comment by bmidgley** [comment]
heh. So I thought I had tested on an original sphero, but it actually was a sphero 2 all along (it's written in a tiny label I see now). I don't actually have an original to try. So the bad behavior is on the latest device running the latest firmware.

**Comment by deadprogram** [comment]
OK, gotcha. Thanks, we will for sure check on it.

**Comment by deadprogram** [comment]
So essentially, @bmidgley appears that data streaming does not return the location data, but instead the odometer data. Your PR looks great, we should make sure the docs show what you figured out, thanks for all that.

So to get the location data, I would think you need to first call `configureLocator` and then receive the data via repeated calls to`readLocator`.

**Comment by bmidgley** [comment]
I don't see any evidence that readLocator can be used to get the location. The spec at https://s3.amazonaws.com/docs.gosphero.com/api/Sphero+Locator+1.1.pdf suggests there are bits to enable location in setDataStreaming "When the Locator X, Locator Y, Velocity X, and Velocity Y bits are set Sphero will stream back position in centimeters and velocity in millimeters per second"

However those two flags are never mentioned again and are not documented in appendix A. I think "locator" as dataSource was written to try to follow the spec, but DATA_SOURCES{1,2} could not be filled out with the corresponding bit pattern without it being disclosed.

The samples in this project appeared to be trying to get at odometer so that's why I thought it would be better for those to be functional samples.

I think a workable full location sample would be one that shows how to use velocity measurements to estimate position.

**Comment by bmidgley** [comment]
edgarsilva wrote in a closed issue that this form would work:

my.sphero.on('locator', function(data){})

but there doesn't appear to be any code to support this

**Comment by deadprogram** [comment]
Hi @bmidgley I spent some time looking into this today, and have corrected the underlying issue in sphero.js to address it. It has nt been released yet, but will be probably tomorrow. 

I will try to work on a cylon-sphero example that uses the corrected locator this evening or tomorrow.

Once again, thanks for all your help on getting this correct.

**Comment by deadprogram** [comment]
Hi, @bmidgley 

I worked on the locator example: https://github.com/hybridgroup/cylon-sphero/tree/master/examples/locator

It works with the `master` branch of the sphero.js library which has not been published to `npm` yet.

**Comment by bmidgley** [comment]
Let's close this one and just track it in the parent project 
https://github.com/orbotix/sphero.js/issues/35
